nodeLinker: node-modules

npmAlwaysAuth: true

npmAuthToken: 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

npmRegistryServer: "https://registry.npmjs.org"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: "@yarnpkg/plugin-version"

yarnPath: .yarn/releases/yarn-3.2.1.cjs
