name: Snap CI

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - "packages/**"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - uses: actions/cache@v3
        id: cache
        with:
          path: '**/node_modules'
          key: uns-yarn-${{ hashFiles('**/yarn.lock') }}
      - run: yarn install
        if: steps.cache.outputs.cache-hit != 'true'
      - run: yarn clean
      - run: yarn build
      - run: yarn test
